baseurl = "https://abuuwais.my.id/"
languageCode = "en-us"
Title = "Triyadi (Abu Uwais)"
theme = "paper"


[Site]
    [Params]
        author = "Triyadi"
        description = "Ini merupakan blog yang kesekian ana, sudah bertahun-tahun ngblog, rasanya membangun lebih asyik ketimbang mengisi konten blog."
        email = "triyaid@gmail.com"
        BaseURL = "https://abuuwais.my.id/" 
        paginate = 10
        paginateetalase = 20   